More Generalizaton
rajdeep1008/kitaab_bot pull request #3
Opened 2016-10-26 13:14 UTC by ashishgulati71

2016-10-26 15:03 UTC, singhsegv requested changes

2016-10-26 15:03 UTC, rajdeep1008 commented on kitaab_bot.py
> +    with open(LOG_PATH, 'a') as log_file:
use the file name logs.txt with LOG_PATH and recreate the request

2016-10-26 15:54 UTC, ashishgulati71 commented on kitaab_bot.py
> +    with open(LOG_PATH, 'a') as log_file:
done

2016-10-26 15:57 UTC, ashishgulati71 commented
done

2016-10-27 16:14 UTC, ashishgulati71 commented
editied

2016-10-27 16:15 UTC, ashishgulati71 reviewed
changed

2016-10-27 16:47 UTC, singhsegv approved these changes

2016-10-27 16:47 UTC, merged